source "https://rubygems.org"
ruby ">= 3.2.0", "< 4.0"
gem "rails", "~> 8.1.3"
gem "pg", "~> 1.6"
gem "puma", "~> 7.0"
gem "bcrypt", "~> 3.1"
gem "rotp", "~> 6.3"
gem "redis", "~> 5.0"
gem "prawn", "~> 2.5"
gem "csv", "~> 3.3"
# Rails 8.1 passes positional options to JSON.parse; JSON 3 requires keywords.
gem "json", ">= 2.9", "< 3"
